export interface VideoThumbnail {
  url: string;
  width: number;
  height: number;
  quality?: string;
}

export interface AuthorThumbnail {
  url: string;
  width: number;
  height: number;
}

// Piped API 타입
export interface PipedStream {
  url: string;
  format: string;
  quality: string;
  mimeType: string;
  codec?: string;
  videoOnly: boolean;
  bitrate: number;
  initStart?: number;
  initEnd?: number;
  indexStart?: number;
  indexEnd?: number;
  width?: number;
  height?: number;
  fps?: number;
  contentLength?: number;
}

export interface PipedVideoInfo {
  title: string;
  description: string;
  uploadDate: string;
  uploader: string;
  uploaderUrl: string;
  uploaderAvatar: string;
  uploaderVerified: boolean;
  uploaderSubscriberCount: number;
  thumbnailUrl: string;
  hls?: string;
  dash?: string;
  lbryId?: string;
  category: string;
  license?: string;
  visibility?: string;
  tags?: string[];
  views: number;
  likes: number;
  dislikes: number;
  duration: number;
  audioStreams: PipedStream[];
  videoStreams: PipedStream[];
  relatedStreams: PipedRelatedStream[];
  subtitles: PipedSubtitle[];
  livestream: boolean;
  proxyUrl: string;
  chapters: PipedChapter[];
}

export interface PipedRelatedStream {
  url: string;
  type: string;
  title: string;
  thumbnail: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatar?: string;
  uploaderVerified: boolean;
  duration: number;
  views: number;
  uploaded: number;
  uploadedDate?: string;
  shortDescription?: string;
  isShort?: boolean;
}

export interface PipedSubtitle {
  url: string;
  mimeType: string;
  name: string;
  code: string;
  autoGenerated: boolean;
}

export interface PipedChapter {
  title: string;
  image: string;
  start: number;
}

export interface PipedSearchResult {
  url: string;
  type: string;
  title: string;
  thumbnail: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatar?: string;
  uploaderVerified: boolean;
  duration: number;
  views: number;
  uploaded: number;
  uploadedDate?: string;
  shortDescription?: string;
  isShort?: boolean;
}

export interface PipedSearchResponse {
  items: PipedSearchResult[];
  nextpage: string;
  suggestion?: string;
  corrected: boolean;
}

export interface PipedTrendingVideo {
  url: string;
  type: string;
  title: string;
  thumbnail: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatar?: string;
  uploaderVerified: boolean;
  duration: number;
  views: number;
  uploaded: number;
  uploadedDate?: string;
  shortDescription?: string;
  isShort?: boolean;
}

// 앱 내부용 통합 타입
export interface VideoSearchResult {
  type: 'video';
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoThumbnails: VideoThumbnail[];
  description: string;
  viewCount: number;
  viewCountText: string;
  publishedText: string;
  lengthSeconds: number;
  liveNow: boolean;
}

export interface TrendingVideo extends VideoSearchResult {}
export interface PopularVideo extends VideoSearchResult {}

export interface VideoInfo {
  title: string;
  videoId: string;
  description: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  authorThumbnail: string;
  subscriberCount: number;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  lengthSeconds: number;
  publishedText: string;
  videoThumbnails: VideoThumbnail[];
  liveNow: boolean;
  hlsUrl?: string;
  dashUrl?: string;
  audioStreams: PipedStream[];
  videoStreams: PipedStream[];
  recommendedVideos: VideoSearchResult[];
}

export interface InvidiousInstance {
  url: string;
  name: string;
  healthy: boolean;
}

export interface DownloadOption {
  url: string;
  quality: string;
  type: 'video' | 'audio' | 'combined';
  format: string;
  size?: string;
  label: string;
}
